name: TeoHeberg Coin Bot

on:
  schedule:
    - cron: '0 */12 * * *' # 每12小时运行一次
  workflow_dispatch:      # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright playwright-stealth requests
          playwright install chromium

      - name: Run script
        env:
          TEO_EMAIL: ${{ secrets.TEO_EMAIL }}
          TEO_PASSWORD: ${{ secrets.TEO_PASSWORD }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python teo_coins.py
